// 2007 button
function change2007() {
    document.body.style.backgroundColor = '#385170'
    document.getElementById('navbar').style.backgroundColor = '#142d4c'
    document.getElementById('h1').innerText = 'On April 19th, 2007...'
    document.getElementById('h1').style.color = '#000000'
    document.getElementById('para').innerText = 'A special day marked the arrival of Kyle Rabkin, born into the world amidst joy and anticipation. With each passing year, April 19 serves as a cherished reminder of the momentous occasion when I entered this world, bringing warmth and happiness to those around them. As the years unfold, April 19 remains a touchstone, a time to honor the journey that began with my arrival and to celebrate the unique individual they have become, embodying hope, resilience, and the boundless potential of life. As you can see in the picture, I start out my life by taking care of the crime on the streets while wearing my batman costume. To access other time periods, click on the buttons below. Otherwise, click on the button at the top that says "On My Birthday..." Enjoy!'
    document.getElementById('para').style.color = '#000000'
    document.getElementById('descrip').style.backgroundColor = '#ececec'
    document.getElementById('image').style.backgroundColor = '#9fd3c7'
    document.getElementById('response-image').src = 'imgs/batman-kyle.jpg'
    document.getElementById('hr1').style.border = 'solid #ececec 2px'
    document.getElementById('hr2').style.border = 'solid #ececec 2px'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#ececec'
    document.getElementById('butt1').style.color = '#000000'
    document.getElementById('butt2').style.backgroundColor = '#9fd3c7'
    document.getElementById('butt2').style.color = '#000000'
    document.getElementById('butt3').style.backgroundColor = '#ececec'
    document.getElementById('butt3').style.color = '#000000'
    document.getElementById('butt4').style.backgroundColor = '#9fd3c7'
    document.getElementById('butt4').style.color = '#000000'
    document.getElementById('butt5').style.backgroundColor = '#ececec'
    document.getElementById('butt5').style.color = '#000000'
    document.getElementById('footer').style.backgroundColor = '#142d4c'
}
// 1943 button
function change1943() {
    document.body.style.backgroundColor = '#393e46'
    document.getElementById('navbar').style.backgroundColor = '#222831'
    document.getElementById('h1').innerText = 'On April 19th, 1943...'
    document.getElementById('h1').style.color = '#000000'
    document.getElementById('para').innerText = "The Warsaw Ghetto Uprising began when Jewish residents in the Warsaw Ghetto, facing imminent deportation to concentration camps by the Nazis, launched a courageous armed resistance. Despite being vastly outnumbered and outgunned, the Jewish fighters valiantly defended themselves for nearly a month, utilizing smuggled weapons and homemade explosives. The uprising, marked by fierce street battles and acts of sabotage, ended on May 16, 1943, with the Nazis brutally crushing the revolt, destroying much of the ghetto, and deporting or killing its inhabitants. Though the uprising ended in defeat, it remains a symbol of Jewish resistance and defiance against Nazi oppression during the Holocaust."
    document.getElementById('para').style.color = '#000000'
    document.getElementById('descrip').style.backgroundColor = '#f2f2f2'
    document.getElementById('image').style.backgroundColor = '#f96d00'
    document.getElementById('response-image').src = 'imgs/warsaw-ghetto-uprising.jpg'
    document.getElementById('hr1').style.border = 'solid #f2f2f2 2px'
    document.getElementById('hr2').style.border = 'solid #f2f2f2 2px'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt1').style.color = '#000000'
    document.getElementById('butt2').style.backgroundColor = '#f96d00'
    document.getElementById('butt2').style.color = '#000000'
    document.getElementById('butt3').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt3').style.color = '#000000'
    document.getElementById('butt4').style.backgroundColor = '#f96d00'
    document.getElementById('butt4').style.color = '#000000'
    document.getElementById('butt5').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt5').style.color = '#000000'
    document.getElementById('footer').style.backgroundColor = '#222831'
}
// 1975 button
function change1975() {
    document.body.style.backgroundColor = '#d3d6db'
    document.getElementById('navbar').style.backgroundColor = '#303841'
    document.getElementById('h1').innerText = 'On April 19th, 1975...'
    document.getElementById('h1').style.color = '#ffffff'
    document.getElementById('para').innerText = "Aryabhata, India's first satellite, was launched into space, marking a historic moment in the nation's space exploration endeavors. Named after the ancient Indian mathematician and astronomer Aryabhata, the satellite was launched by the Soviet Union. Aryabhata's successful deployment into orbit marked India's entry into space research and technology. This satellite was primarily dedicated to scientific experiments, focusing on areas such as X-ray astronomy and solar physics. The launch of Aryabhata represented a significant milestone for India's space program, laying the groundwork for future satellite missions and advancements in space technology."
    document.getElementById('para').style.color = '#ffffff'
    document.getElementById('descrip').style.backgroundColor = '#3a4750'
    document.getElementById('image').style.backgroundColor = '#be3144'
    document.getElementById('response-image').src = 'imgs/aryabhata.jpg'
    document.getElementById('hr1').style.border = 'solid #3a4750 2px'
    document.getElementById('hr2').style.border = 'solid #3a4750 2px'
    document.getElementById('wat').style.color = '#000000'
    document.getElementById('butt1').style.backgroundColor = '#3a4750'
    document.getElementById('butt1').style.color = '#ffffff'
    document.getElementById('butt2').style.backgroundColor = '#be3144'
    document.getElementById('butt2').style.color = '#ffffff'
    document.getElementById('butt3').style.backgroundColor = '#3a4750'
    document.getElementById('butt3').style.color = '#ffffff'
    document.getElementById('butt4').style.backgroundColor = '#be3144'
    document.getElementById('butt4').style.color = '#ffffff'
    document.getElementById('butt5').style.backgroundColor = '#3a4750'
    document.getElementById('butt5').style.color = '#ffffff'
    document.getElementById('footer').style.backgroundColor = '#303841'
    document.getElementsByClassName('::-webkit-scrollbar').style.width = '30px'
}
// 1993 button
function change1993() {
    document.body.style.backgroundColor = '#acdcee'
    document.getElementById('navbar').style.backgroundColor = '#2e94b9'
    document.getElementById('h1').innerText = 'On April 19th, 1993...'
    document.getElementById('h1').style.color = '#000000'
    document.getElementById('para').innerText = "The Waco siege took place, which culminated in a tragic and deadly confrontation between federal authorities and members of the Branch Davidians religious sect in Waco, Texas, USA. The siege began on February 28, 1993, when the Bureau of Alcohol, Tobacco, and Firearms (ATF) attempted to execute a search warrant at the Mount Carmel Center, the compound where the Branch Davidians lived. The raid resulted in a shootout, leaving four ATF agents and six Branch Davidians dead. The subsequent siege lasted for 51 days. On April 19, 1993, the standoff ended in a catastrophic fire that engulfed the compound, resulting in the deaths of 76 people, including many women and children."
    document.getElementById('para').style.color = '#000000'
    document.getElementById('descrip').style.backgroundColor = '#f0fbff'
    document.getElementById('image').style.backgroundColor = '#2e94b9'
    document.getElementById('hr1').style.border = 'solid #f0fbff 2px'
    document.getElementById('hr2').style.border = 'solid #f0fbff 2px'
    document.getElementById('wat').style.color = '#000000'
    document.getElementById('butt1').style.backgroundColor = '#f0fbff'
    document.getElementById('butt1').style.color = '#000000'
    document.getElementById('butt2').style.backgroundColor = '#2e94b9'
    document.getElementById('butt2').style.color = '#000000'
    document.getElementById('butt3').style.backgroundColor = '#f0fbff'
    document.getElementById('butt3').style.color = '#000000'
    document.getElementById('butt4').style.backgroundColor = '#2e94b9'
    document.getElementById('butt4').style.color = '#000000'
    document.getElementById('butt5').style.backgroundColor = '#f0fbff'
    document.getElementById('butt5').style.color = '#000000'
    document.getElementById('footer').style.backgroundColor = '#2e94b9'
}
// 1995 button
function change1995() {
    document.body.style.backgroundColor = '#fe7847'
    document.getElementById('navbar').style.backgroundColor = '#4c0b2f'
    document.getElementById('h1').innerText = 'On April 19th, 1995...'
    document.getElementById('h1').style.color = '#ffffff'
    document.getElementById('para').innerText = "A heinous act of domestic terrorism shook the United States when a truck bomb detonated outside the Alfred P. Murrah Federal Building in Oklahoma City, Oklahoma. The explosion, orchestrated by Timothy McVeigh and accomplices Terry Nichols and Michael Fortier, devastated the building and surrounding area, resulting in the deaths of 168 people, including many children, and injuring hundreds more. The attack, which targeted a symbol of federal government authority, inflicted profound grief and shock nationwide. The Oklahoma City bombing remains a somber reminder of the threat posed by domestic terrorism and the enduring need for vigilance in safeguarding against such acts of violence."
    document.getElementById('para').style.color = '#ffffff'
    document.getElementById('descrip').style.backgroundColor = '#ca2c3f'
    document.getElementById('image').style.backgroundColor = '#a21738'
    document.getElementById('response-image').src = 'imgs/alfred-bombing.jpg'
    document.getElementById('hr1').style.border = 'solid #4c0b2f 2px'
    document.getElementById('hr2').style.border = 'solid #4c0b2f 2px'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#ca2c3f'
    document.getElementById('butt1').style.color = '#ffffff'
    document.getElementById('butt2').style.backgroundColor = '#a21738'
    document.getElementById('butt2').style.color = '#ffffff'
    document.getElementById('butt3').style.backgroundColor = '#ca2c3f'
    document.getElementById('butt3').style.color = '#ffffff'
    document.getElementById('butt4').style.backgroundColor = '#a21738'
    document.getElementById('butt4').style.color = '#ffffff'
    document.getElementById('butt5').style.backgroundColor = '#ca2c3f'
    document.getElementById('butt5').style.color = '#ffffff'
    document.getElementById('footer').style.backgroundColor = '#4c0b2f'
}
// 2018 button
function change2018() {
    document.body.style.backgroundColor = '#f5c7f7'
    document.getElementById('navbar').style.backgroundColor = '#27296d'
    document.getElementById('h1').innerText = 'On April 19th, 2018...'
    document.getElementById('h1').style.color = '#ffffff'
    document.getElementById('para').innerText = "King Mswati III of Swaziland made a historic announcement during celebrations marking his 50th birthday and the country's 50th anniversary of independence, declaring that Swaziland would henceforth be known as the Kingdom of Eswatini. The name change, which had been under consideration for several years, was seen as a symbolic gesture toward national sovereignty and cultural heritage. While the move was celebrated by supporters as a positive step towards decolonization and self-determination, it also sparked debates and criticisms, with some questioning the timing and practical implications of the change amidst ongoing socio-economic challenges in the kingdom."
    document.getElementById('para').style.color = '#ffffff'
    document.getElementById('descrip').style.backgroundColor = '#a393eb'
    document.getElementById('image').style.backgroundColor = '#5e63b6'
    document.getElementById('hr1').style.border = 'solid #27296d 2px'
    document.getElementById('hr2').style.border = 'solid #27296d 2px'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#a393eb'
    document.getElementById('butt1').style.color = '#ffffff'
    document.getElementById('butt2').style.backgroundColor = '#5e63b6'
    document.getElementById('butt2').style.color = '#ffffff'
    document.getElementById('butt3').style.backgroundColor = '#a393eb'
    document.getElementById('butt3').style.color = '#ffffff'
    document.getElementById('butt4').style.backgroundColor = '#5e63b6'
    document.getElementById('butt4').style.color = '#ffffff'
    document.getElementById('butt5').style.backgroundColor = '#a393eb'
    document.getElementById('butt5').style.color = '#ffffff'
    document.getElementById('footer').style.backgroundColor = '#27296d'
}