// 2007 button
function change2007() {
    document.body.style.backgroundColor = '#385170'
    document.getElementById('navbar').style.backgroundColor = '#142d4c'
    document.getElementById('h1').innerText = 'On April 19th, 2007...'
    document.getElementById('h1').style.color = '#000000'
    document.getElementById('para').innerText = 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis nostrum debitis vero, error laboriosam dolorum natus totam cumque esse vitae, autem dolorem molestiae cum quod reiciendis possimus placeat nam sint quis. Fugit quia vel, odio tempora, unde omnis suscipit natus quasi culpa fuga facilis voluptatibus aspernatur iure ea modi distinctio! Ad dolorem sapiente deleniti iure. Dignissimos magnam rerum possimus, sint perspiciatis rem inventore quis! Consectetur quis, a, numquam culpa at veniam recusandae iusto unde debitis qui vel ullam ab sit est velit quos totam inventore nemo dolorem necessitatibus alias! Ea illum neque repudiandae voluptates rerum amet molestiae facere placeat, officiis velit magni ad, itaque a cumque nisi soluta omnis ullam odio eligendi magnam labore! Nostrum voluptas minus debitis expedita repellat hic, quis excepturi eaque maiores veritatis quas tenetur dolorum quia enim magni harum quidem itaque qui temporibus nam possimus necessitatibus officiis! Blanditiis omnis facilis magnam cumque officiis atque, quis vitae!'
    document.getElementById('para').style.color = '#000000'
    document.getElementById('descrip').style.backgroundColor = '#ececec'
    document.getElementById('image').style.backgroundColor = '#9fd3c7'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#ececec'
    document.getElementById('butt1').style.color = '#000000'
    document.getElementById('butt2').style.backgroundColor = '#9fd3c7'
    document.getElementById('butt2').style.color = '#000000'
    document.getElementById('butt3').style.backgroundColor = '#ececec'
    document.getElementById('butt3').style.color = '#000000'
    document.getElementById('butt4').style.backgroundColor = '#9fd3c7'
    document.getElementById('butt4').style.color = '#000000'
    document.getElementById('butt5').style.backgroundColor = '#ececec'
    document.getElementById('butt5').style.color = '#000000'
    document.getElementById('footer').style.backgroundColor = '#142d4c'
}
// 1943 button
function change1943() {
    document.body.style.backgroundColor = '#393e46'
    document.getElementById('navbar').style.backgroundColor = '#222831'
    document.getElementById('h1').innerText = 'On April 19th, 1943...'
    document.getElementById('h1').style.color = '#000000'
    document.getElementById('para').innerText = 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis nostrum debitis vero, error laboriosam dolorum natus totam cumque esse vitae, autem dolorem molestiae cum quod reiciendis possimus placeat nam sint quis. Fugit quia vel, odio tempora, unde omnis suscipit natus quasi culpa fuga facilis voluptatibus aspernatur iure ea modi distinctio! Ad dolorem sapiente deleniti iure. Dignissimos magnam rerum possimus, sint perspiciatis rem inventore quis! Consectetur quis, a, numquam culpa at veniam recusandae iusto unde debitis qui vel ullam ab sit est velit quos totam inventore nemo dolorem necessitatibus alias! Ea illum neque repudiandae voluptates rerum amet molestiae facere placeat, officiis velit magni ad, itaque a cumque nisi soluta omnis ullam odio eligendi magnam labore! Nostrum voluptas minus debitis expedita repellat hic, quis excepturi eaque maiores veritatis quas tenetur dolorum quia enim magni harum quidem itaque qui temporibus nam possimus necessitatibus officiis! Blanditiis omnis facilis magnam cumque officiis atque, quis vitae!'
    document.getElementById('para').style.color = '#000000'
    document.getElementById('descrip').style.backgroundColor = '#f2f2f2'
    document.getElementById('image').style.backgroundColor = '#f96d00'
    document.getElementById('wat').style.color = '#ffffff'
    document.getElementById('butt1').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt1').style.color = '#000000'
    document.getElementById('butt2').style.backgroundColor = '#f96d00'
    document.getElementById('butt2').style.color = '#000000'
    document.getElementById('butt3').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt3').style.color = '#000000'
    document.getElementById('butt4').style.backgroundColor = '#f96d00'
    document.getElementById('butt4').style.color = '#000000'
    document.getElementById('butt5').style.backgroundColor = '#f2f2f2'
    document.getElementById('butt5').style.color = '#000000'
    document.getElementById('footer').style.backgroundColor = '#222831'
}
// 1975 button
function change1975() {
    document.body.style.backgroundColor = '#d3d6db'
    document.getElementById('navbar').style.backgroundColor = '#303841'
    document.getElementById('h1').innerText = 'On April 19th, 1975...'
    document.getElementById('h1').style.color = '#ffffff'
    document.getElementById('para').innerText = 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officiis nostrum debitis vero, error laboriosam dolorum natus totam cumque esse vitae, autem dolorem molestiae cum quod reiciendis possimus placeat nam sint quis. Fugit quia vel, odio tempora, unde omnis suscipit natus quasi culpa fuga facilis voluptatibus aspernatur iure ea modi distinctio! Ad dolorem sapiente deleniti iure. Dignissimos magnam rerum possimus, sint perspiciatis rem inventore quis! Consectetur quis, a, numquam culpa at veniam recusandae iusto unde debitis qui vel ullam ab sit est velit quos totam inventore nemo dolorem necessitatibus alias! Ea illum neque repudiandae voluptates rerum amet molestiae facere placeat, officiis velit magni ad, itaque a cumque nisi soluta omnis ullam odio eligendi magnam labore! Nostrum voluptas minus debitis expedita repellat hic, quis excepturi eaque maiores veritatis quas tenetur dolorum quia enim magni harum quidem itaque qui temporibus nam possimus necessitatibus officiis! Blanditiis omnis facilis magnam cumque officiis atque, quis vitae!'
    document.getElementById('para').style.color = '#ffffff'
    document.getElementById('descrip').style.backgroundColor = '#3a4750'
    document.getElementById('image').style.backgroundColor = '#be3144'
    document.getElementById('wat').style.color = '#000000'
    document.getElementById('butt1').style.backgroundColor = '#3a4750'
    document.getElementById('butt1').style.color = '#ffffff'
    document.getElementById('butt2').style.backgroundColor = '#be3144'
    document.getElementById('butt2').style.color = '#ffffff'
    document.getElementById('butt3').style.backgroundColor = '#3a4750'
    document.getElementById('butt3').style.color = '#ffffff'
    document.getElementById('butt4').style.backgroundColor = '#be3144'
    document.getElementById('butt4').style.color = '#ffffff'
    document.getElementById('butt5').style.backgroundColor = '#3a4750'
    document.getElementById('butt5').style.color = '#ffffff'
    document.getElementById('footer').style.backgroundColor = '#303841'
}